fcm:
	g++ fcm.cpp -Wall -Wextra -o3 -march=native -mtune=native -flto -ffast-math -fomit-frame-pointer -funroll-loops -o fcm

fcm_debug:
	g++ fcm.cpp -Wall -Wextra -ggdb -o fcm_debug

clean:
	rm -rf fcm fcm_debug